import { Jost } from "next/font/google";
import "./globals.css";
import ScrollRestoration from "./component/ScrollRestoration";

const jost = Jost({
  subsets: ["latin"],
  variable: "--body-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ScrollRestoration />
        {children}
      </body>
    </html>
  );
}
